sudo: required
language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=webaudio
  matrix:
    - OCAML_VERSION=4.01
    - OCAML_VERSION=4.02
