addons:
  firefox: "45.0"
sudo: required
language: c
before_install:
  - sudo apt-get -qq update
  - sudo usermod -a -G audio travis
  - sudo apt-get install -y xvfb
  - sudo apt-get install -y portaudio19-dev
  - sudo apt-get install -y libasound2-dev alsa-utils alsa-oss
  - sudo bash test/prep-dummy-soundcard.sh
install:
  - sudo -H pip install selenium==2.53.6
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script:
  - sudo -E sudo -u $USER -E bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=webaudio
    - EXTRA_REMOTES=git://github.com/johnelse/opam-repo-johnelse
  matrix:
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.03
